server:
  port: 10001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6060/eureka
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dc?characterEncoding=utf-8
    username: remote
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true  #格式化sql